name: task_1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # get: ^4.6.6
  dartz: ^0.10.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  lottie: ^3.1.2
  flutter_screenutil: ^5.9.3
  readmore: ^3.0.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
